# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  run:
    cmds:
      - go run ./cmd/app
  migrate:up:
    cmds:
      - goose -dir migrations postgres "${DATABASE_URL}" up
  migrate:down:
    cmds:
      - goose -dir migrations postgres "${DATABASE_URL}" down
    
