# https://taskfile.dev

version: '3'

tasks:
  auth:run:
    dir: './auth'
    cmds:
      - go run ./cmd/app
  
  messages:run:
    dir: './messages'
    cmds:
      - go run ./cmd/app

  auth:migrate:up:
    dotenv: ['auth/.env']
    cmds:
      - goose -dir migrations postgres "${DATABASE_URL}" up

  auth:migrate:down:
    dotenv: ['auth/.env']
    cmds:
      - goose -dir migrations postgres "${DATABASE_URL}" reset

  messages:migrate:up:
    dotenv: ['messages/.env']
    cmds:
      - goose -dir migrations postgres "${DATABASE_URL}" up

  messages:migrate:down:
    dotenv: ['messages/.env']
    cmds:
      - goose -dir migrations postgres "${DATABASE_URL}" reset

  migrate:up:all:
    cmds:
      - task: auth:migrate:up
      - task: messages:migrate:up

  run:all:
    cmds:
      - task: auth:run
      - task: messages:run
