// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID          `json:"id"`
	Name      *string            `json:"name"`
	IsGroup   *bool              `json:"is_group"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatMember struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

type Message struct {
	ID        uuid.UUID          `json:"id"`
	ChatID    uuid.UUID          `json:"chat_id"`
	SenderID  uuid.UUID          `json:"sender_id"`
	Content   string             `json:"content"`
	IsEdited  *bool              `json:"is_edited"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CryptedRefreshToken *string            `json:"crypted_refresh_token"`
}
