// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToChat(ctx context.Context, arg AddUserToChatParams) error
	CreateChat(ctx context.Context, isGroup *bool) (Chat, error)
	CreateGroupChat(ctx context.Context, name *string) (Chat, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteChat(ctx context.Context, id uuid.UUID) error
	DeleteMessage(ctx context.Context, id uuid.UUID) error
	DeleteMessages(ctx context.Context, chatID uuid.UUID) error
	EditMessage(ctx context.Context, arg EditMessageParams) error
	GetChatMembers(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error)
	GetMessages(ctx context.Context, chatID uuid.UUID) ([]Message, error)
	GetUserChats(ctx context.Context, userID uuid.UUID) ([]Chat, error)
	RemoveUserFromChat(ctx context.Context, arg RemoveUserFromChatParams) error
}

var _ Querier = (*Queries)(nil)
